sudo: false
cache:
  apt: true
  cargo: false # manual below, see https://levans.fr/rust_travis_cache.html 
  ccache: true
  go: true
  directories:
  - $HOME/.cache
  - $HOME/.cargo
  - $HOME/.rustup
  - $HOME/bin
env:
  global:
  - "PATH=$PATH:$HOME/bin"
  - protoc_version=3.1.0
language: rust
rust: "1.32.0"
before_cache:
  - rm -rf $HOME/.cargo/registry
matrix:
  include:
    - env: task=rust-1.32
      # addons:
      #   apt:
      #     packages:
      #     - clang
      #     - lcov
      before_install:
        - ./script/install-protoc $protoc_version
        # - rustup component add rustfmt-preview
        # - cargo install --force cargo-cov
      script: build_go=0 ./all.bash
      after_success: bash <(curl -s https://codecov.io/bash)
    - env: task=rust-beta
      language: rust
      rust: beta
      before_install:
        - ./script/install-protoc $protoc_version
      script: build_go=0 ./all.bash
    - env: task=client-go
      language: go
      go: "1.11"
      before_install: ./script/install-protoc $protoc_version
      script: build_rust=0 ./all.bash
      before_cache: rm -f $HOME/.cache/go-build/log.txt
      after_success: bash <(curl -s https://codecov.io/bash)
