coverage:
  precision: 0

ignore:
  - "**/*.pb.go"
  - "**/Cargo.lock"
  - "**/Cargo.toml"
  - "build/.*"
  - "cmd/iodin/src/proto/iodin.rs"
  - "pigpio-sys/src/bindings-arm-linux.rs"
  - "qemu/.*"
  - "target/.*"
